// Writes LICENCES.md: every npm and Rust dependency with its licence, and the ones that need a human to look (copyleft, unknown).
// Run from the project root:  node scripts/licence-report.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const rows = [];

// npm: from the lock file, which records each package's licence.
const lock = JSON.parse(readFileSync('package-lock.json', 'utf8'));
for (const [path, p] of Object.entries(lock.packages)) {
  if (!path) continue;
  const name = path.replace(/^.*node_modules\//, '');
  rows.push({ eco: 'npm', name, version: p.version ?? '', licence: normalise(p.license), dev: !!p.dev });
}

// Rust: from cargo's own metadata.
const meta = JSON.parse(execFileSync('cargo', ['metadata', '--manifest-path', 'src-tauri/Cargo.toml', '--format-version', '1', '--locked'], { encoding: 'utf8', maxBuffer: 1 << 28 }));
for (const p of meta.packages) {
  if (p.name === 'steminize') continue;
  rows.push({ eco: 'cargo', name: p.name, version: p.version, licence: normalise(p.license), dev: false });
}

function normalise(l) {
  if (!l) return 'UNKNOWN';
  if (typeof l === 'object') return normalise(l.type);
  return String(l).replace(/\s+/g, ' ').trim();
}

// What a person should look at: any copyleft licence, and anything that did not say.
const COPYLEFT = /(^|[^L])GPL|LGPL|AGPL|MPL|EPL|CDDL|CC-BY-SA|OFL|SEE LICENSE|UNLICENSED|UNKNOWN/i;
// A licence that is an OR of choices is fine if one of the choices is permissive.
const PERMISSIVE = /\b(MIT|Apache-2\.0|BSD-2-Clause|BSD-3-Clause|ISC|0BSD|Unlicense|CC0-1\.0|Zlib|BlueOak-1\.0\.0|Python-2\.0|CC-BY-4\.0|Unicode-3\.0|Unicode-DFS-2016|BSL-1\.0)\b/;
const needsLook = (r) => COPYLEFT.test(r.licence) && !(/ OR /.test(r.licence) && PERMISSIVE.test(r.licence));

const counts = new Map();
for (const r of rows) counts.set(r.licence, (counts.get(r.licence) ?? 0) + 1);
const flagged = rows.filter(needsLook).sort((a, b) => a.licence.localeCompare(b.licence) || a.name.localeCompare(b.name));

const out = [];
out.push('# Dependency licences', '');
out.push(`Generated by \`node scripts/licence-report.mjs\` on ${new Date().toISOString().slice(0, 10)}. ${rows.length} packages (${rows.filter((r) => r.eco === 'npm').length} npm, ${rows.filter((r) => r.eco === 'cargo').length} Rust crates, including build tools and platform-specific crates that are not in every installer).`, '');
out.push('Steminize itself is MIT. This lists what it is built from, so a person can check each licence is compatible with how Steminize is distributed. It is not legal advice.', '');
out.push('## What the flagged ones mean (written by hand; check it still holds after updates)', '');
out.push('- **soundtouchjs (LGPL-2.1)** and **@breezystack/lamejs (LGPL-3.0)** are shipped inside the web app\'s JavaScript (tempo and pitch in the normal engine; MP3 export). LGPL asks that people can replace the library with their own version. That holds while Steminize\'s source is public, since anyone can rebuild with a different copy. It would **not** hold for a closed-source or paid version without work: swap them (the native engine already uses the MIT-licensed Signalsmith Stretch instead of SoundTouch) or ship them as separately replaceable files. See the paid-version note in BACKLOG.md.');
out.push('- **cssparser, cssparser-macros, dtoa-short, selectors, option-ext (MPL-2.0, Rust)** come in through Tauri and the web view. MPL is file-level copyleft: fine when the files are used unmodified and their source stays available, which is the case.');
out.push('- **lightningcss and its platform builds (MPL-2.0, npm, dev only)** are used by the build tooling and are not in any installer.');
out.push('- Two Rust crates offer `MIT OR Apache-2.0 OR LGPL-2.1-or-later`: the permissive choices are taken, so nothing is owed.');
out.push('- The separation models (Demucs weights, via the StemSplit ONNX exports) and Basic Pitch are not code dependencies, so they are not listed here; see the credits in About.', '');
out.push('## Needs a look', '');
if (flagged.length) {
  out.push('Copyleft or unstated licences. Most are fine for an app that only uses them as separate libraries, but each should be read once.', '');
  out.push('| Package | Version | Licence | From | Dev only |', '|---|---|---|---|---|');
  for (const r of flagged) out.push(`| ${r.name} | ${r.version} | ${r.licence} | ${r.eco} | ${r.dev ? 'yes' : ''} |`);
} else out.push('None.');
out.push('', '## Counts by licence', '', '| Licence | Packages |', '|---|---|');
for (const [l, n] of [...counts].sort((a, b) => b[1] - a[1])) out.push(`| ${l} | ${n} |`);
out.push('', '## Every package', '');
for (const eco of ['npm', 'cargo']) {
  out.push(`### ${eco === 'npm' ? 'npm' : 'Rust crates'}`, '', '| Package | Version | Licence |', '|---|---|---|');
  for (const r of rows.filter((x) => x.eco === eco).sort((a, b) => a.name.localeCompare(b.name))) out.push(`| ${r.name} | ${r.version} | ${r.licence}${r.dev ? ' (dev)' : ''} |`);
  out.push('');
}
writeFileSync('LICENCES.md', out.join('\n'));
console.log(`${rows.length} packages; ${flagged.length} need a look; wrote LICENCES.md`);
