// Native song library for the desktop app: the same job as the web app's browser-storage (OPFS)
// library (see src/library.ts), but backed by plain files under the OS's app-data directory,
// since WebKitGTK (the Linux webview) doesn't support OPFS's write API even with every relevant
// experimental switch turned on ("Backend does not support this operation").
//
// Layout, deliberately identical to the OPFS one: <app-local-data>/library/<song-id>/meta.json
// plus one FLAC file per stem/take. A backup zip made by either side can be restored on the other.
//
// Metadata is passed through as an opaque JSON string in both directions: its shape is owned by
// the frontend (src/library.ts) and evolves there, so Rust never parses or depends on its fields.

use tauri::{AppHandle, Manager};

pub(crate) fn lib_root(app: &AppHandle) -> Result<std::path::PathBuf, String> {
    let dir = app.path().app_local_data_dir().map_err(|e| e.to_string())?.join("library");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

/// Song ids are generated by the frontend (a date plus a random suffix) and file names are stem/take
/// names plus ".flac" or "meta.json"; neither should ever contain a path separator, but both cross the
/// IPC boundary as plain strings, so this is checked defensively rather than trusted.
pub(crate) fn safe_component<'a>(s: &'a str, what: &str) -> Result<&'a str, String> {
    if s.is_empty() || s == "." || s == ".." || s.contains(['/', '\\']) {
        return Err(format!("invalid {what}"));
    }
    Ok(s)
}

fn song_dir(app: &AppHandle, id: &str) -> Result<std::path::PathBuf, String> {
    Ok(lib_root(app)?.join(safe_component(id, "song id")?))
}

#[derive(serde::Serialize)]
pub struct SongEntry {
    id: String,
    meta: String,
}

/// Every song's meta.json, with its id (the folder name). A folder without one is an interrupted
/// save from a previous run (see saveSong in library.ts: stem files are written before meta.json,
/// specifically so an incomplete save can be recognised this way) and is cleaned up here, the same
/// as the OPFS backend does when it finds one.
#[tauri::command]
pub fn lib_list(app: AppHandle) -> Result<Vec<SongEntry>, String> {
    let root = lib_root(&app)?;
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&root).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        if !entry.file_type().map_err(|e| e.to_string())?.is_dir() {
            continue;
        }
        let id = entry.file_name().to_string_lossy().into_owned();
        match std::fs::read_to_string(entry.path().join("meta.json")) {
            Ok(meta) => out.push(SongEntry { id, meta }),
            Err(_) => {
                let _ = std::fs::remove_dir_all(entry.path());
            }
        }
    }
    Ok(out)
}

#[tauri::command]
pub fn lib_write_meta(app: AppHandle, id: String, meta: String) -> Result<(), String> {
    let dir = song_dir(&app, &id)?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("meta.json"), meta).map_err(|e| e.to_string())
}

/// Writes one stem or take file. Takes id/name as headers and the bytes as the raw request body
/// (see open_link and ytdlp_read for the same raw-IPC pattern used elsewhere in this app), since a
/// song's FLAC stems can be several MB each and JSON-encoding them would be needlessly slow.
#[tauri::command]
pub fn lib_write_file(app: AppHandle, request: tauri::ipc::Request<'_>) -> Result<u64, String> {
    let header = |name: &str| -> Result<&str, String> {
        request.headers().get(name).ok_or_else(|| format!("missing {name} header"))?.to_str().map_err(|e| e.to_string())
    };
    let id = header("x-song-id")?.to_string();
    let name = header("x-file-name")?.to_string();
    let tauri::ipc::InvokeBody::Raw(bytes) = request.body() else {
        return Err("expected a raw request body".into());
    };
    let dir = song_dir(&app, &id)?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    std::fs::write(dir.join(safe_component(&name, "file name")?), bytes).map_err(|e| e.to_string())?;
    Ok(bytes.len() as u64)
}

#[tauri::command]
pub fn lib_read_file(app: AppHandle, id: String, name: String) -> Result<tauri::ipc::Response, String> {
    let dir = song_dir(&app, &id)?;
    let bytes = std::fs::read(dir.join(safe_component(&name, "file name")?)).map_err(|e| e.to_string())?;
    Ok(tauri::ipc::Response::new(bytes))
}

/// Every file in a song's folder (including meta.json), for building a backup zip.
#[tauri::command]
pub fn lib_list_files(app: AppHandle, id: String) -> Result<Vec<String>, String> {
    let dir = song_dir(&app, &id)?;
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        if entry.file_type().map_err(|e| e.to_string())?.is_file() {
            out.push(entry.file_name().to_string_lossy().into_owned());
        }
    }
    Ok(out)
}

/// Removes one take's file (a take being discarded); missing is not an error, matching the OPFS side.
#[tauri::command]
pub fn lib_remove_file(app: AppHandle, id: String, name: String) -> Result<(), String> {
    let dir = song_dir(&app, &id)?;
    match std::fs::remove_file(dir.join(safe_component(&name, "file name")?)) {
        Ok(()) | Err(_) => Ok(()),
    }
}

#[tauri::command]
pub fn lib_delete(app: AppHandle, id: String) -> Result<(), String> {
    let dir = song_dir(&app, &id)?;
    match std::fs::remove_dir_all(&dir) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::safe_component;

    #[test]
    fn rejects_anything_that_could_leave_the_library_folder() {
        assert!(safe_component("2026-09-27-ab12cd", "id").is_ok());
        assert!(safe_component("Bass (2)", "name").is_ok());
        assert!(safe_component("", "id").is_err());
        assert!(safe_component(".", "id").is_err());
        assert!(safe_component("..", "id").is_err());
        assert!(safe_component("../elsewhere", "id").is_err());
        assert!(safe_component("a/b", "name").is_err());
        assert!(safe_component("a\\b", "name").is_err());
        assert!(safe_component("/etc/passwd", "id").is_err());
    }
}
